apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-small-pvc
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi  # adjust the storage size as needed
  storageClassName: csi-cinder-high-speed  # reference the StorageClass