apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: ollama
spec:
  selector:
    app: open-webui
  ports:
  - name: http
    port: 3000
    targetPort: 8080
    nodePort: 30080
  type: NodePort